-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Kullanicilar"
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "EPosta" character varying(50) NOT NULL,
    "Sifre" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."IsArayanlar"
(
    "KullaniciId" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Adi" character varying(50) NOT NULL,
    "Soyadi" character varying(50) NOT NULL,
    "DogumYili" date NOT NULL,
    "TcKimlikNo" character(11) NOT NULL,
    "SifreTekrari" character varying(50) NOT NULL,
    "EPostaOnayi" boolean NOT NULL,
    PRIMARY KEY ("KullaniciId")
);

CREATE TABLE public."IsVerenler"
(
    "KullaniciId" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "SirketAdi" character varying(50) NOT NULL,
    "Website" character varying(50) NOT NULL,
    "TelefonNo" character(10) NOT NULL,
    "SifreTekrari" character varying(50) NOT NULL,
    "EPostaOnayi" boolean NOT NULL,
    PRIMARY KEY ("KullaniciId")
);

CREATE TABLE public."Personeller"
(
    "KullaniciId" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Adi" character varying(50) NOT NULL,
    "Soyadi" character varying(50) NOT NULL,
    "DogumYili" date NOT NULL,
    PRIMARY KEY ("KullaniciId")
);

CREATE TABLE public."KullaniciMevcutMuKontrolleri"
(
    "Id" integer NOT NULL,
    "TcKimlikNoKullanimdaLog" character varying(50) NOT NULL,
    "MernisLog" character varying(50) NOT NULL,
    "EPostaKullanimdaLog" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."SirketMevcutMuKontrolleri"
(
    "Id" integer NOT NULL,
    "HrmsPersonelOnayiLog" character varying(50) NOT NULL,
    "EPostaDomainLog" character varying(50) NOT NULL,
    "EPostaKullanimdaLog" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."IsPozisyonlari"
(
    "IsPozisyonuId" integer NOT NULL,
    "Id" integer NOT NULL,
    "IsPozisyonuAdi" character varying(50) NOT NULL,
    PRIMARY KEY ("IsPozisyonuId")
);

CREATE TABLE public."IsPozisyonuKontrolleri"
(
    "IsPozisyonuId" integer NOT NULL,
    "IsPozisyounKayitliMiLog" character varying(50),
    PRIMARY KEY ("IsPozisyonuId")
);

ALTER TABLE public."IsVerenler"
    ADD FOREIGN KEY ("KullaniciId")
    REFERENCES public."Kullanicilar" ("Id")
    NOT VALID;


ALTER TABLE public."Personeller"
    ADD FOREIGN KEY ("KullaniciId")
    REFERENCES public."Kullanicilar" ("Id")
    NOT VALID;


ALTER TABLE public."IsArayanlar"
    ADD FOREIGN KEY ("KullaniciId")
    REFERENCES public."Kullanicilar" ("Id")
    NOT VALID;


ALTER TABLE public."KullaniciMevcutMuKontrolleri"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."IsArayanlar" ("KullaniciId")
    NOT VALID;


ALTER TABLE public."SirketMevcutMuKontrolleri"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."IsVerenler" ("KullaniciId")
    NOT VALID;


ALTER TABLE public."IsPozisyonlari"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."IsArayanlar" ("KullaniciId")
    NOT VALID;


ALTER TABLE public."IsPozisyonlari"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."IsVerenler" ("KullaniciId")
    NOT VALID;


ALTER TABLE public."IsPozisyonuKontrolleri"
    ADD FOREIGN KEY ("IsPozisyonuId")
    REFERENCES public."IsPozisyonlari" ("IsPozisyonuId")
    NOT VALID;

END;