-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Musteriler"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "MusteriNo" character varying(10) NOT NULL,
    "KanalId" integer NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public."Musteriler"
    IS 'Temel sinif / Pascal Casing ';

COMMENT ON COLUMN public."Musteriler".id
    IS 'Her tablonun id kolonu olmalı / TcNo veya MusteriNo primary key olmaz (diger tablolara bagimlilik olmamali)';

COMMENT ON COLUMN public."Musteriler"."MusteriNo"
    IS 'Tüzel ve gerçek her musterinin kendisine atanmis bir numarasi olacak';

COMMENT ON COLUMN public."Musteriler"."KanalId"
    IS 'Musterinin bankaya ulastigi kanalin bilgisi';

CREATE TABLE public."GercekMusteriler"
(
    "MusteriId" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Ad" character varying(50) NOT NULL,
    "Soyad" character varying(50) NOT NULL,
    "TcKimlikNo" character(11) NOT NULL,
    PRIMARY KEY ("MusteriId")
);

COMMENT ON TABLE public."GercekMusteriler"
    IS 'Musteriler tablosunu miras alıyor/';

COMMENT ON COLUMN public."GercekMusteriler"."MusteriId"
    IS 'Tablonun id si temel tablodan miras alınarak MusteriId kolonuna atanıyor.';

COMMENT ON COLUMN public."GercekMusteriler"."Ad"
    IS 'Ad kolonu ayri olusturulmali';

COMMENT ON COLUMN public."GercekMusteriler"."Soyad"
    IS 'Soyad kolonu ayri olusturulmali';

COMMENT ON COLUMN public."GercekMusteriler"."TcKimlikNo"
    IS 'Sabit karakter verilmeli';

CREATE TABLE public."TuzelMusteriler"
(
    "MusteriId" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Unvan" character varying(50) NOT NULL,
    "VergiNo" character(10) NOT NULL,
    PRIMARY KEY ("MusteriId")
);

COMMENT ON TABLE public."TuzelMusteriler"
    IS 'Open Closed Principle / Musteriler ve GercekMusteriler tabloları etkilenmez.';

COMMENT ON COLUMN public."TuzelMusteriler"."MusteriId"
    IS 'Musteriler tablosunun id sini miras alıyor.';

COMMENT ON COLUMN public."TuzelMusteriler"."VergiNo"
    IS 'on karakter sabit /karakter sayisi degismez';

CREATE TABLE public."Adresler"
(
    "Id" integer NOT NULL,
    "MusteriId" integer NOT NULL,
    "AdresDetay" character varying(250) NOT NULL,
    PRIMARY KEY ("Id")
);

COMMENT ON TABLE public."Adresler"
    IS 'Her bir musterinin en az bir tane adresi olacak/ birden fazla adres bir musteri icin tutulabilir.';

CREATE TABLE public."Bilancolar"
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "MusteriId" integer NOT NULL,
    "Tarih" date NOT NULL,
    "Tutar" money NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."TicariFaaliyetler"
(
    "Id" integer NOT NULL,
    "GercekMusteriId" integer NOT NULL,
    "BaslangicTarihi" date,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."Kanallar"
(
    "Id" integer NOT NULL,
    "KanalAdı" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
);

ALTER TABLE public."GercekMusteriler"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."Musteriler" (id)
    NOT VALID;


ALTER TABLE public."TuzelMusteriler"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."Musteriler" (id)
    NOT VALID;


ALTER TABLE public."Adresler"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."Musteriler" (id)
    NOT VALID;


ALTER TABLE public."Bilancolar"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."Musteriler" (id)
    NOT VALID;


ALTER TABLE public."TicariFaaliyetler"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."Musteriler" (id)
    NOT VALID;


ALTER TABLE public."TicariFaaliyetler"
    ADD FOREIGN KEY ("GercekMusteriId")
    REFERENCES public."GercekMusteriler" ("MusteriId")
    NOT VALID;


ALTER TABLE public."Adresler"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."GercekMusteriler" ("MusteriId")
    NOT VALID;


ALTER TABLE public."Adresler"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."TuzelMusteriler" ("MusteriId")
    NOT VALID;


ALTER TABLE public."Bilancolar"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."GercekMusteriler" ("MusteriId")
    NOT VALID;


ALTER TABLE public."Bilancolar"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."TuzelMusteriler" ("MusteriId")
    NOT VALID;


ALTER TABLE public."Adresler"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."GercekMusteriler" ("MusteriId")
    NOT VALID;


ALTER TABLE public."Adresler"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."TuzelMusteriler" ("MusteriId")
    NOT VALID;


ALTER TABLE public."Kanallar"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."Musteriler" (id)
    NOT VALID;

END;